### PR TITLE
Improve flag replacement.  Implement generic libretro-core_src_compile.

### PR DESCRIPTION
**Pull request by sjnewbury**
This will need changes to the ebuilds to pass extra parameters to emake via "myemakeargs" and drop all ebuild src_compile's which just specify the makefile.

I you're okay with it I'll make a start on the ebuilds.

### CODE REVIEW

**Comment by jason-oliveira** [comment]
some of the makefiles seem to be in different subdirs, so I'm not sure this script will work 100% with all the libretro cores. has this been tested on all of them?

**Comment by stefan-gr** [comment]
Sorry for the late response.
That's fine, I have already merged #59 though so the eclass needs to be updated again. I hope you didn't already work on the ebuilds since many updates got through the merge.
I can help over the weekend with that if you wish.

> some of the makefiles seem to be in different subdirs, so I'm not sure this script will work 100% with all the libretro cores. has this been tested on all of them?

It should work in theory since ${S} is set in the affected ebuilds, otherwise we need to introduce a additional variable.

**Comment by sjnewbury** [comment]
That cool.  I did obviously give it some testing before the pull request. ;-)

**Comment by stefan-gr** [comment]
I didn't start moving everything over yet so if you have pending changes please push them to the pr.
I don't think I will make it this week because of too much work and fixing broken ebuilds.
When I get to it I will begin in reverse alphabetical order. Hopefully, I will finally get some alone time next week.

**Comment by stefan-gr** [comment]
It is done.

**Comment by sjnewbury** [comment]
On Mon, 2017-03-06 at 12:14 -0800, stefan-gr wrote:
> It is done.
Nice.  I've been busily distracted with fixing other things! :-)

**Pull request merged**
