### PR TITLE
dev-games/godot: updates (3.0.2) & fixes

### PR DESCRIPTION
**Pull request by nado**
* add 3.0.2
* update 9999 and 2.1.4 to reflect llvm minimum version set upstream
* upgrade 2.1.4, 3.0.2, 9999 to EAPI 7
* reset Manifest as some archives had changed on github

Package-Manager: Portage-2.3.36, Repoman-2.3.9
RepoMan-Options: --force
Manifest-Sign-Key: CDA35ADCF05EFBD41130F52FC98B954CC6EF78A4

Close: https://github.com/stefan-gr/abendbrot/issues/109

### CODE REVIEW

**Comment by hanetzer** [comment]
@nado I wouldn't edit the EAPI in-place, nor the deps. For the latter sort of change, you will
probably require a rebuild depending on the situation, so a revbump is a better way to go about
it.

**Comment by nado** [comment]
Got it, I'll revbump 2.1.4 and add the slots I forgot.

**Comment by hanetzer** [comment]
And on another note, you should really not make pull requests using your master branch.
Suppose you have another thing you want to fix, you'll want to have a separate branch
for each thing. Diffucult to do if you're using master. Ideally master should be the same as
the repo you cloned/forked from.

**Comment by hanetzer** [comment]
And one other thing; you shouldn't inherit eutils here. I know it was used in previous versions, but
that's a bit of an excessive and lazy way to do things. eutils inherits many other eclasses, not all of
which are actually needed, and implements some functions not available in lower eapi. All you really
seem to need is desktop.eclass.

**Comment by nado** [comment]
Thanks for the tip on desktop.eclass, I admit I was a bit lazy and did not want to check every call to see which eclass I should have used.

Don't worry about my git branches, I use master only for these kind of PR, where I'm not really interested in anything else but godot and I'll force reset everything back when merged, otherwise I create one branch per thing I'm working on ;)

I am also gonna delay the merge a bit to have this patch [1] integrated in gentoo tree and authorize EAPI 7 with scons, I don't know why repoman wasn't triggered on my previous attempt.

Thanks for the feedback

[1] https://archives.gentoo.org/gentoo-dev/message/9f10fb7a3985a1296dd13982652d056e

**Comment by nado** [comment]
Hi, just giving some news, I am working on those ebuilds (3.0.5 instead of 3.0.4), scons/EAPI=7 is handled and I am trying to disable builtin libs. I will make another PR later from a separate branch since I’ve made one now.

May I rm all previous ebuilds but the latest (before my changes) to reduce repoman noise ?

**Pull request closed without merging**
