### PR TITLE
RetroArch 1.4.0 and 1.4.1 Releases

### PR DESCRIPTION
**Pull request by jason-oliveira**
According to the buildbot for RetroArch, a new version was released on 1/24/2017. I have updated all the packages to reflect new commits.

### CODE REVIEW

**Comment by barbudreadmon** [comment]
You didn't fix the audio_driver issue i mentioned in #58

**Comment by jason-oliveira** [comment]
you're right. I didn't. fixed now, and now everything builds. Thanks for the info.

**Comment by barbudreadmon** [comment]
Actually, audio_filters still exist, it is in libretro-common/audio/dsp_filters/

**Comment by jason-oliveira** [comment]
Weird. there are no .so files anywhere in those directories. I'll upload new ebuilds soon to reflect the needed changes (outside nonexistant .so files)

**Comment by jason-oliveira** [comment]
New 1.4.1 release on February 2nd, so going through all the repositories to update everything to that date. hold tight for a bunch of new packages.

**Pull request merged**
