### PR TITLE
eclass/libretro-core: Support USE=custom-cflags by hacking Makefiles

### PR DESCRIPTION
**Pull request by sjnewbury**

### CODE REVIEW

**Comment by stefan-gr** [comment]
Thanks,

please include `-maxdepth 1 -mindepth 1` to make find not recursive, otherwise `target-libretro/Makefile` in `bsnes-libretro` acquires CFLAGS in the linking stage. I have default LDFLAGS that include -O1, thus sed applies to that file twice.

I will emerge the other cores tomorrow to see if something comes up.

**Comment by sjnewbury** [comment]
On Thu, 2016-12-22 at 13:58 -0800, stefan-gr wrote:
> Thanks,
> please include -maxdepth 1 -mindepth 1 to make find not recursive,
> otherwise target-libretro/Makefile in bsnes-libretro acquires CFLAGS
> in the linking stage. I have default LDFLAGS that include -O1, thus
> sed applies to that file twice.
> I will emerge the other cores tomorrow to see if something comes up.
> 
I started of with just the one "sed", it made sense to do it
recursively.  I later needed to add the second one and didn't notice
the bug.  I've changed them both to globs.  Will need to check all
cores still get their flags changed.

I've made it a second commit, would you prefer I squash them?

**Comment by stefan-gr** [comment]
> I started of with just the one "sed", it made sense to do it recursively. I later needed to add the second one and didn't notice the bug. I've changed them both to globs. Will need to check all cores still get their flags changed.

I have almost no time to run further merges with this but 40 cores were already building without problem yesterday so think this is alright to merge in a few days when you checked the flags.

> I've made it a second commit, would you prefer I squash them?

No worries, I don't think that this repo will bloat too much with small commits.

**Comment by stefan-gr** [comment]
Thanks for the work, I didn't find anything wrong with the changes.

**Comment by sjnewbury** [comment]
I've just noticed that pretty much all the cores ignore CC/CXX/LD and LDFLAGS passed through the environment, and need them provided on the make command line.

emake CC=$(tc-getCC) etc works fine.  But it would be best to to this centrally through the eclass.  I'm going to implement this and refactor or eliminate the src_compile for each core.  I'll then create a new pull request unless you have an objection.

**Pull request merged**
