### PR TITLE
Retroarch: The Big Pull Request

### PR DESCRIPTION
**Pull request by leycec**
Happy New Year, Stefan! Long time no code party. :santa: 

We live to game another year. Time churns on, and so do the Retroarch ebuilds. Except not really. It's not your fault at all, but they're kind of in "bit-rot" at the moment. All projects have their growing pains as they hit acne-scarred puberty and the mainstream eye. Retroarch is no exception.

Quality assurance on the live Retroarch repository has _always_ been sporadic at best – but it's getting worse. `retroarch-9999.ebuild` failed a few days ago on my system with the following compile-time error:

```
remote.c: In function ‘rarch_remote_poll’:
remote.c:227:20: error: ‘rarch_remote_t’ has no member named ‘net_fd’
          if (handle->net_fd[user] < 0)
                    ^
In file included from /usr/include/sys/select.h:128:0,
                 from /usr/include/sys/types.h:219,
                 from ./libretro-common/include/file/file_path.h:29,
                 from remote.c:27:
remote.c:231:23: error: ‘rarch_remote_t’ has no member named ‘net_fd’
          FD_SET(handle->net_fd[user], &fds);
                       ^
In file included from /usr/include/sys/types.h:219:0,
                 from ./libretro-common/include/file/file_path.h:29,
                 from remote.c:27:
remote.c:231:23: error: ‘rarch_remote_t’ has no member named ‘net_fd’
          FD_SET(handle->net_fd[user], &fds);
                       ^
remote.c:233:31: error: ‘rarch_remote_t’ has no member named ‘net_fd’
          ret = recvfrom(handle->net_fd[user], buf,
                               ^
Makefile:126: recipe for target 'obj-unix/remote.o' failed
make: *** [obj-unix/remote.o] Error 1
```

This has probably been fixed upstream by now. But it doesn't matter! It shouldn't have happened in the first place. I _needed_ to play [Castlevania: Aria of Sorrow](http://www.gamefaqs.com/gba/589456-castlevania-aria-of-sorrow) (also known as "Greatest Game of All Time and Space Ever") at 3:00 AM, like a junk-food junky needs that last bag of deep-fried wood chips. But stupid Retroarch just wouldn't compile.

I was sufficiently flummoxed that I decided to fix this the only way I know how: **downstream.** Because I'd rather eat a mutant spore for post-fallout breakfast than hit yet _another_ bad Retroarch commit.

That's right. The time has come!

## Live and Stable Retroarch Logic Unified

The first commit of this pull request centralizes logic for installing both the live and stable Retroarch packages into a single ebuild: `retroarch-9999.ebuild`. Numerous live ebuilds in the Portage tree do this (including Kodi, if memory serves), so I thought: "Why not?"

To spare our fellow gamers from similar compilation woes, the live Retroarch package has been soft-masked with empty keywords and must now be explicitly unmasked by adding the following line to `/etc/portage/package.accept_keywords`:

    >=games-emulation/retroarch-1.2.2 **

To force recompilation of Retroarch whenever a Retroarch dependency is recompiled (e.g., via `emerge @preserved-rebuild`), all Retroarch dependencies are now suffixed with [EAPI 5](https://devmanual.gentoo.org/ebuild-writing/eapi)-style `:slot=` syntax (e.g., `media-libs/libsdl2:0=[joystick]` rather than `media-libs/libsdl2[joystick]`).

For conformance with `media-libs/mesa`, two USE flags have been changed:

* The `gles` USE flag has been renamed to `gles2`. This both streamlines the list of ebuild dependencies _and_ supports users globally enabling the common `gles2` USE flag.
* The `openvg` USE flag has been removed entirely. "Woo, there! _Wat_?", you may be muttering. Allow me to explain. For unknown reasons, the most recent stable Mesa ebuild (`mesa-11.0.6.ebuild`) has dropped support for OpenVG and hence the `openvg` USE flag. Retaining this USE flag in the Retroarch ebuild catastrophically causes Portage to downgrade Mesa without informing the user of the reason why – even when the `--verbose-conflicts` option is passed to `emerge`. I should know. This happened to me yesterday. **And it absolutely sucked.** I spent literally a day attempting to resolve the following inexplicable `emerge -uavDN @world` error:

```
[blocks B      ] =media-libs/mesa-10.3.7-r1 ("=media-libs/mesa-10.3.7-r1" is blocking app-eselect/eselect-opengl-1.3.1-r4)
```

Imagine my displeasure when I finally isolated this to Retroarch, only to realize with gnawing horror that it was _actually_ Mesa's fault for silently dropping support for the `openvg` USE flag in `mesa-11.0.6.ebuild` and failing to tell anybody. Or maybe it's _actually, actually_ Portage's fault for failing to output anything meaningful for blockers, even when you tell it to. (You decide.)

## Stable Retroarch Releases

The second commit of this pull request adds an ebuild for the newest stable Retroarch release: **1.2.2**.

For maintainability, I've elected to symlink `retroarch-1.2.2.ebuild` to `retroarch-9999.ebuild`. This may or may not be a good thing. In my [overlay](https://github.com/leycec/raiagent), I typically symlink the newest stable ebuild for a package to that package's live ebuild. This reduces copy-and-paste errors and saves quite a bit of time.

**Your mileage may vary.** If you think this really sucks, I'd be happy to just copy `retroarch-9999.ebuild` to `retroarch-1.2.2.ebuild` instead.

## Retroarch in 2016: A Bold Start to an Old Pasttime

*Aaaa-nd*... that's it.

I'm excited to see what Retroarch 1.3.0 brings to the table. (_Maybe good stuff?_) I'm also contemplating transitioning from [EmulationStation](http://www.emulationstation.org/) to Kodi. Curse my natural-born laziness and lust for easy GUIs!

Have a great start to 2016. Take care, Stefan.

### CODE REVIEW

**Comment by leycec** [comment]
@stefan-gr _Pinging Stefan. Pinging Stefan!_

"Stefan, your singular expertise (and commit access) is needed in the retro lobby." :video_game:

**Comment by leycec** [comment]
**Hot tamales of childhood joy!**

Retroarch [1.3.0](http://www.libretro.com/index.php/retroarch-1-3-released) was _just_ released, so I'll probably augment this pull request with support for that as well. Back to the volunteer slave mines... :gem:

**Comment by leycec** [comment]
**It is done.** Retroarch 1.2.2 and 1.3.1 (the most recent stable release) are _both_ supported now, and mostly behave as expected.

Due to an [outstanding issue](https://github.com/libretro/RetroArch/issues/2663) in Retroarch >= 1.3.0, netplay support is _always_ enabled in both `retroarch-1.3.1.ebuild` and `retroarch-9999.ebuild`. Hence, the `netplay` USE flag is currently ignored. With any luck, we'll be able to revert this soon.

Also, Retroarch is now installed to the standard Gentoo directories for games (e.g., `/etc/games`, `/usr/games`, `/usr/share/games`, `/var/games`). To simplify these sorts of path changes in the future, I've added a few new global variables to the ebuild. All's fair in love and code!

**Comment by stefan-gr** [comment]
Whoops, sorry for the long delay I'm currently not in reach of my gentoo machine. Happy new year to you too. You take a burden off my heart with the live and stable ebuild. That's something I was thinking of doing this year too but I probably would never have through of symlinking them. I'm kinda glad AoS pushed you to do this work since I didn't even realize that the build failed again, what a gaffe. :umbrella:

> To force recompilation of Retroarch whenever a Retroarch dependency is recompiled (e.g., via emerge @preserved-rebuild), all Retroarch dependencies are now suffixed with EAPI 5-style :slot= syntax (e.g., media-libs/libsdl2:0=[joystick] rather than media-libs/libsdl2[joystick]).


Dat EAPI slot recompile magic is a really nice addition. I like your pull requests, always new things to learn with them. :smiley:
> The openvg USE flag has been removed entirely.


I was actually aware that openvg will be dropped but I completely forgot about it while waiting for it to happen. :frowning:
> I'm also contemplating transitioning from EmulationStation to Kodi.


EmulationStation never clicked right for me. I can't get over the fact that the text in descriptions is just cutting off instead of omitting a line or fading away.
> The glui USE flag has been dropped


I liked glui so I will look into material gui in the next few days after I set up a gentoo vm for portable overlay testing which i should have done ages ago.
> All's fair in love and code.


Don't worry about messing with the ebuild it was quite a mess to begin with. I'm glad you took time to comment your changes.

I'm kind of excited getting home and trying out your changes, will merge asap. Let's hope the games eclass will not get dropped so that nobody needs to change the paths in the config files again. I'm already eager to see what sort of trouble repoman will spit out when i run it. :smiley:

Thank you for your contribution. If you want I can give you collaborator access so that you don't need to wait for me having time which I surprisingly have very little as of late.

**Comment by leycec** [comment]
> ...I'm currently not in reach of my gentoo machine. 

_wat_

No Gentoo == No Fun. How did this tragedy come to pass, old friend?

> I'm kinda glad AoS pushed you to do this work...

**AoS:** making grizzled men feel young again since 2003.

It Is Good

> I was actually aware that openvg will be dropped...

_wat_

Nobody ever tells me anythin'! I am a tad confused, though: OpenVG _looks_ like it's still in development by the Khronos Group. Well, [sort of](https://en.wikipedia.org/wiki/OpenVG#History). And Mesa _looks_ like it still supports OpenVG. Did the Gentoo community just decide that OpenVG sucked ugly balls and hence wasn't worth supporting?

> EmulationStation never clicked right for me. I can't get over the fact that the text in descriptions is just cutting off instead of omitting a line or fading away.

**Ugh.** I haven't noticed that cockup on my end. But if I did, I'd definitely be turned off EmulationStation too.

In my case, it was the performance. Ever since the stabilization of Mesa 11.0.x, OpenGL has become... _different_ on my machine. Some games (notably Unity-based cRPGS such as "Shadowrun: Dragonfall") have seen dramatic FPS increases. Others (notably Retroarch) are no longer usable at all in OpenGL mode. Thank the German Gods for SDL2 support in Retroarch. (Still, I miss muh shaders!)

EmulationStation _appeared_ to be unaffected. Until I actually tried to play a game, at which point EmulationStation cut my FPS **in half** merely by running in the background. Needless to say, EmulationStation is no longer installed.

> ...after I set up a gentoo vm for portable overlay testing which i should have done ages ago.

_Woh!_ Sounds like you're on the lonely road and/or lonely plane and/or lonely train again. Will the venomous vipers in upper management never leave you alone?

> Let's hope the games eclass will not get dropped so that nobody needs to change the paths in the config files again.

I will have a well-sharpened sword ready for that grim day.

> If you want I can give you collaborator access so that you don't need to wait for me having time which I surprisingly have very little as of late.

_Aww_. Quite kind of yah! I don't mind the wait, actually. The back-and-forth banter of these pull requests is almost a blessing in the dark days of Winter. :snowman: 

But... **yes.** I'd be happy to accept commit access and muck up your long years of hard work.

**Comment by stefan-gr** [comment]
>No Gentoo == The Dead Zone. How did this tragedy come to pass, old friend?

I forgot to repaste my CPU, it's now throwing cache errors like repoman dependency problems. It's already solved, though now I need to make sure to never go over -j4 but I really want to sit it out until ZEN hits the market.

>I am a tad confused, though: OpenVG looks like it's still in development by the Khronos Group. Well, sort of. And Mesa looks like it still supports OpenVG. Did the Gentoo community just decide that OpenVG sucked ugly balls and hence wasn't worth supporting?

I noticed it over a year ago with the mesa live ebuilds, it suddenly stopped compiling with openvg and the answer was: "It's dropped". I wonder why it took so long until release.

>Ever since the stabilization of Mesa 11.0.x, OpenGL has run... different on my machine.

Noticed no difference on my end. Running with radeon and my HD 5850 and still rocking. :smiley:

>Wooh! Sounds like you're on the lonely road and/or lonely plane and/or lonely train again. Will the venomous vipers in upper management never leave you be?

Hah, don't worry I'm my own manager but now the customers are the slave drivers. :sweat:

>But... yes. I'd be happy to accept commit access and muck up your long years of hard work.

Thanks but don't feel too obligated to make any changes in this repo. I just through it would be alright to give you access since you are already so invested in retroarch and your ebuilds have nice comments.

**Comment by leycec** [comment]
> I forgot to repaste my CPU...

_Oh, man._ That's happened in my house, too. And everyone paid the price.

Well, mostly me.

> ...but I really want to sit it out until ZEN hits the market.

**AMD.** You burned me once before! I remember Bulldozer. And I don't forgive.

But... _yes_. It'll be great to have genuine competition in the CPU sphere again. Intel, you die! I also like the raw numbers I'm seeming concerning the ZEN architecture: 14nm process (_yes, please_), 3D high-bandwidth memory (_oh, man; oh, man_), and 40% higher instructions-per-clock (IPC).

On boardroom paper, it all sounds great. Let's just hope it survives the push to market.

> Running with radeon and my HD 5850 and still rocking. :smile: 

I... I'm kinda poor. When the choice is fun gaming or non-fun bills, non-fun always seem to win. I'm still milking the last litre of GPU juice from an ancient artifact of power: the **HD 4330**!

I bet you didn't even know the numbers went that low.

> Hah, don't worry I'm my own manager but now the customers are the slave drivers. :sweat: 

My wife and I are right there with you. We run a small [scientific consultancy](http://www.mindshines.com/index.html) out of the idyllic, brutal Canadian wilderness. The chittering squirrels upstairs are wrestling under the frozen roof as we speak.

Sometimes, I think _they're_ our best customers.

> I just thought it would be alright to give you access since you are already so invested in retroarch and your ebuilds have nice comments.

That's right! I'm a Retroarch man through and through. Thanks to the [psychology of previous investment](https://en.wikipedia.org/wiki/Psychology_of_previous_investment), I'm now locked into supporting Retroarch for the remainder of my natural existence.

I'm cool either way. Commit access: :+1: No commit access: :+1:

**Comment by stefan-gr** [comment]
>AMD, you burned me once. I remember Bulldozer. And I don't forgive.

Hah, I skipped them in favor of my phenom x2 t1090. I still cry about the missing instruction sets but i sucked it up since it didn't feel like a worthwhile upgrade. Intel doesn't come into the equation just for the principle of it.
>On boardroom paper, it sounds great. Let's just hope it survives the unforgiving push to market.

It must, or i have to give in to the Intel overlords.
>I bet you didn't even know the numbers went that low.

Oh wow, they don't get OpenGl4+ anymore do they? Do the free drivers even get updates for that card? I'm interested in how long it will work on current kernel and xorg/wayland.


> My wife and I are right there with you. We run a small scientific consultancy out of the idyllic, brutal Canadian wilderness. The chittering squirrels upstairs are wrestling under our frozen roof as we speak.
> 
> Sometimes, I think they're our best customers.

Sounds comfy. I'm sitting here in the cold/warm mud like weather in germany trying to get the motivation to update my site to use sql, instead of spreadsheets, to show menu card forms. Never touch what works, eh? I hope no more than 10 people will use it at once or the server will DDoSs itself with my horrible unoptimized php code.

**Pull request merged**
